spring:
    profiles.active: prod
    datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}

server:
    error:
        include-stacktrace: never

api:
    security:
        secret: ${JWT_SECRET:123456}
